# Generated by Django 2.2.2 on 2019-07-03 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.IntegerField(default=0, verbose_name='visits')),
                ('file_code', models.CharField(max_length=8, verbose_name='code')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time')),
                ('path', models.CharField(max_length=32, verbose_name='download path')),
                ('name', models.CharField(default='', max_length=32, verbose_name='file name')),
                ('file_size', models.CharField(max_length=10, verbose_name='file size')),
                ('ip', models.CharField(default='', max_length=32, verbose_name='ip address')),
            ],
        ),
    ]
